//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_GiaBao.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichChieu()
        {
            this.Ves = new HashSet<Ve>();
        }
    
        public string id { get; set; }
        public System.DateTime ThoiGianChieu { get; set; }
        public string idDinhDang { get; set; }
        public Nullable<int> GiaVe { get; set; }
        public int TrangThai { get; set; }
    
        public virtual DinhDangPhim DinhDangPhim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
